language: node_js
node_js:
  - "stable"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token # we’ll add this secret in Travis next
  local_dir: build # folder to publish
  on:
    branch: master # only deploy when pushing to main
